{{- define "environment.newrelic" }}
- name: NEW_RELIC_LICENSE_KEY
  value: {{ .Values.newrelic.key }}
- name: NEW_RELIC_APP_NAME
  value: "{{ .Release.Name }}-{{ .Values.env }}"
- name: NEW_RELIC_SYNC_STARTUP
  value: "true"
- name: NEW_RELIC_LOG
  value: "STDOUT"
- name: NEW_RELIC_LABELS
  value: "app:{{ .Release.Name }};namespace:{{ .Release.Namespace }};env:{{ .Values.env }};team:{{ .Values.global.team }};component:{{ .Values.global.component }}"
- name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
  value: "true"
{{- end }}