apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    version: {{ .Chart.Version }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    team: {{ .Values.global.team }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: {{ .Release.Name }}
      port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP